### ISSUE TITLE
mu-argus - Target record swapping 

### ISSUE THREAD

**Issue by ViragMistry** [ppdewolf/muargus#5]
Good afternoon, 

I was trying to read the mu-argus manual, "MUmanual5.1.3". I could not able to get the detailed information to apply target record swapping method using mu-argus software. 
Can you please guide me, the reference page number or topic to get the details on it or it will be great if you can provide the manual on target record swapping to implemennt in mu-argus software?

Thank you in advance, 
Kind regards, 
Virag

**Comment by ppdewolf** [comment]
Hi Virag,

targeted record swapping is part of mu-argus since version 5.1.5, so obviously not specified in the Mumanual5.1.3 ;-)

I would refer you to the sdcTools organization on gtihub [here](https://github.com/sdcTools) and its mu-argus repository for the latest releases. 
The most recent release is [5.1.7 build 4](https://github.com/sdcTools/muargus/releases/tag/v5.1.7b4) and is accompanied by an additional document: [quickreference to using targeted record swapping](https://github.com/sdcTools/muargus/releases/download/v5.1.7b4/QuickReferenceTRS5.1.7.pdf)

**Comment by ViragMistry** [comment]
Thank a lot for your quick revert. I got it.
